/home/graemeg/bin/ppc386 -S2cai -O1 -g -gl -ve \
  -Fu/home/graemeg/programming/tiOPF2/FBLib/lib/ \
  -Fi/home/graemeg/programming/tiOPF2/Source/Core/ \
  -Fu/home/graemeg/programming/tiOPF2/Source/Core/ \
  -Fu/home/graemeg/programming/tiOPF2/Source/Options/ \
  -Fu/home/graemeg/programming/tiOPF2/Source/GUI/ \
  -Fu. -FElib/i386-linux/ \
  -dLINK_CSV -dLINK_FBL -dLINK_TAB -dLINK_XMLLIGHT -dUseCThreads \
  tiOPF.pas


