#!/bin/sh
# Build script for tiOPF using 64bit Free Pascal Compiler

TIOPF="/opt/dailybuilds/tiopf"
FBLIB="$TIOPF/3rdParty/FBLib/lib/x86_64-linux"
FPC="/opt/fpc_2.3.1/bin/ppcx64"

#   -Fu$FBLIB/ \

$FPC -MObjFPC -S2cai -O1 -gl -ve \
  -Fi$TIOPF/Core/ \
  -Fu$TIOPF/Core/ \
  -Fu$TIOPF/Options/ \
  -Fu$TIOPF/GUI/ \
  -Fu. -FE$TIOPF/Compilers/FPC/lib/x86_64-linux/ \
  -dLINK_CSV -dLINK_TAB -dLINK_XMLLIGHT -dLINK_SQLDB_IB -dUseCThreads \
  $TIOPF/Compilers/FPC/tiOPF.pas

