/opt/fpc/bin/fpc -S2cgi -O1 -gl -ve -l \
  -Fu/opt/lazarus/components/fpcunit/console/lib/i386-linux/ \
  -Fu/opt/lazarus/packager/units/i386-linux/ \
  -Fu/home/graemeg/programming/3rdParty/tiOPF2/Source/3rdParty/FBLib/lib/i386-linux/ \
  -Fu/opt/dailybuilds/tiopf/Compilers/FPC/lib/i386-linux/ \
  -Fi/opt/dailybuilds/tiopf/Core/ \
  -Fu/opt/dailybuilds/tiopf/UnitTests/Common/ \
  -Fu/opt/dailybuilds/tiopf/UnitTests/Tests/ \
  -Fu. \
  -o/opt/dailybuilds/tiopf/UnitTests/Text/textrunner \
  -FU/opt/dailybuilds/tiopf/UnitTests/Text/_Dcu \
  -dLINK_CSV -dLINK_TAB -dLINK_XMLLIGHT -dLINK_SQLDB_IB -dLINK_SQLDB_PQ \
  -dUseCThreads \
  /opt/dailybuilds/tiopf/UnitTests/Text/textrunner.pas

