#!/bin/sh
# Build script for tiOPF's TextRunner using 64bit Free Pascal Compiler

TIOPF="/home/graemeg/programming/tiopf/Source"
FBLIB="$TIOPF/3rdParty/FBLib/lib/x86_64-linux"
FPC="/home/graemeg/programming/fpc/bin/fpc"
LAZ="/home/graemeg/programming/lazarus"

$FPC -S2cgi -O1 -gl -ve -l \
  -Fu$LAZ/components/fpcunit/console/lib/x86_64-linux/ \
  -Fu$LAZ/packager/units/x86_64-linux/ \
  -Fu$TIOPF/Compilers/FPC/lib/x86_64-linux/ \
  -Fi$TIOPF/Core/ \
  -Fu$TIOPF/UnitTests/Common/ \
  -Fu$TIOPF/UnitTests/Tests/ \
  -Fu. \
  -o$TIOPF/UnitTests/Text/textrunner64 \
  -FU$TIOPF/UnitTests/Text/_Dcu \
  -dLINK_CSV -dLINK_TAB -dLINK_XMLLIGHT -dLINK_SQLDB_IB -dUseCThreads \
  $TIOPF/UnitTests/Text/textrunner.pas

